version: "3.8"

services:
  app:
    build: ./app/
    container_name: app
    ports:
      - "8000:80"
    volumes:
      - ./app:/app

  gateway:
    build: ./gateway/
    container_name: gateway
    ports:
      - "3000:30"

volumes:
    elasticsearch_data:
        driver: local