version: "3.8"

services:
  userproducts:
    build: ./userProducts/
    ports:
      - "8000:80"
    container_name: userproducts
    volumes:
      - ./logs:/app/logs

  ordersclient:
    build: ./ordersClient/
    ports:
      - "8100:81"
    container_name: ordersclient
    volumes:
      - ./logs:/app/logs

  filebeat:
    build: ./filebeat/
    container_name: filebeat
    volumes:
      - ./logs:/src/logs
    depends_on:
      - userproducts
      - ordersclient
      - elasticsearch
      - kibana
    network_mode: "host"

  elasticsearch:
    build: ./elasticsearch/
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    build: ./kibana/
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  gateway:
    build: ./gateway/
    container_name: gateway
    ports:
      - "3000:30"
    volumes:
      - ./logs:/var/log/nginx

volumes:
    elasticsearch_data:
        driver: local